### ISSUE TITLE
make "fails" after build

### ISSUE THREAD

**Issue by arrowgent** [torunar/flying-toasters-xscreensaver#3]
```
gcc -o bin/flying-toasters src/flying-toasters.c -L/usr/lib -lX11 -lXpm -s -W -Wall
./bin/flying-toasters -windowed
XIO:  fatal IO error 11 (Resource temporarily unavailable) on X server ":0"
      after 2055 requests (2011 known processed) with 158 events remaining.
make: *** [Makefile:4: run] Error 1
```

this is because after exiting the -windowed open, make will fail
this should be changed so that it does not automatically open and instead suggests "how to open"

an auto failure like this isnt good for an automated make

Makefile:
```
run:
	echo "./bin/flying-toasters -windowed"
```
works fine for me.  make finished successfully.

**Comment by torunar** [comment]
Valid point. I set default make target to build instead of build and run: https://github.com/torunar/flying-toasters-xscreensaver/commit/6a3cae6a5222866308dbd5a28aa9820bf4f38f4e
