### ISSUE TITLE
release - v1.1.0 built with newer dependencies: glibc

### ISSUE THREAD

**Issue by arrowgent** [torunar/flying-toasters-xscreensaver#4]
```
./flying-toasters_v1.1.0: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ./flying-toasters_v1.1.0)
```

its pretty common to release with the latest newest desktop OS
for older os, people will need to compile their own!

(ubuntu 18.04)

**Comment by torunar** [comment]
Hi there. Not sure about the best approach to this problem, but let's see if something I came up with will work.

@arrowgent Try `flying-toasters-legacy` from https://github.com/torunar/flying-toasters-xscreensaver/releases/tag/v1.1.1. I built this binary on Docker image with Ubuntu 18.04, it works on my Ubuntu 22.04. Does it work for you?

**Comment by arrowgent** [comment]
it does indeed run.   
im not saying you need to support legacy OS which are rarely in use.  just making note of compatibility with older glibc
github & launchpad offer some support for building with older OS (ubuntu/debian)

i can also note the size of your ver1.1.1 to mine is:

```
46240 flying-toasters_git_make_1.1.0
46232 flying-toasters-legacy_1.1.1
```

**Comment by torunar** [comment]
Thanks for testing things out. From now on I'll be building binaries using the environment with older OS in it.
