### ISSUE TITLE
Black screen instead of screensaver on Arch

### ISSUE THREAD

**Issue by N-Upchurch** [torunar/flying-toasters-xscreensaver#6]
When running via `./flying-toasters -windowed`, everything works as expected, but when added to `.xscreensaver` like so:
```
  GL:                           hextrail --root                             \n\
                                /usr/local/bin/flying-toasters     \n\
```
...only a black screen appears when clicking the preview button. 

I am running EndeavourOS / Arch.

**Comment by torunar** [comment]
Hi. Which version of toasters are you running. Is it v1.1.1?

**Comment by N-Upchurch** [comment]
Yes, it's the latest. I also tried building from source.

**Comment by torunar** [comment]
Cool, thanks for confirming. I’m not planning to close this issue, but since I don’t have Arch installed, it will take some to debug. I’ll take a look on other xscreenaver modules to find out what can be a fix here.

**Comment by torunar** [comment]
Please check if https://github.com/torunar/flying-toasters-xscreensaver/releases/tag/v1.2.0 works for you. I changed the way the screensaver window is initialized using [the implementation](https://github.com/Zygo/xscreensaver/blob/a7be2fd2981da28322be0872b11e1059d6571e6d/utils/vroot.h) from xscreensaver itself, hope it fixes the issue.

**Comment by N-Upchurch** [comment]
This works! Thank you.
