### ISSUE TITLE
how do i install this in android

### ISSUE THREAD

**Issue by kingofcube** [torunar/flying-toasters-xscreensaver#7]
I don't have a rooted phone

**Comment by torunar** [comment]
jwz, the author of xscreensaver, also provides an Android app: https://play.google.com/store/apps/details?id=org.jwz.android.xscreensaver

But from what I see in the changelog, screensavers (or “hacks” in xscreensaver terms) are added by rebuilding the app.

I’m afraid I can’t help you more here. You can try contacting jwz and ask him for an advice: [jwz@jwz.org](mailto:jwz@jwz.org).
